title: Kira Long's Website
tagline: Kira Long, PhD Candidate at University of Illinois at Urbana-Champaign
description: >-
  Kira Long is a PhD candidate in the Program in Ecology, Evolution, and Conservation Biology (PEEC)
  at the University of Illinois at Urbana-Champaign.

name: Kira Long
email: kiralong778@gmail.com
twitter_username: kmlong7
github_username:  kiralong

# Build settings
url: "https://kiralong.github.io"
# theme: minima

lsi: true

plugins:
  - jekyll-feed
  - classifier-reborn

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
